### ISSUE TITLE
Installer didn't work

### ISSUE THREAD

**Issue by HaffASE** [phatblinkie/mn_installer#12]
After downloading logs show this:

> Create pirl-node systemd unit file, install, and start.
> Successfully created /etc/pirlnode-env with new tokens
> Failed to execute operation: No such file or directory
> Failed to restart pirlnode.service: Unit pirlnode.service not found.
> Create pirl-marlin systemd unit file, install, and start.
> Wait 5 seconds for pirlnode to run before initializing marlin
> chown: cannot access '/root/.marlin/': No such file or directory
> Something went wrong with initializing marlin folder
> Please run '/usr/bin/marlin init' manually after installation
> Failed to execute operation: No such file or directory
> Failed to restart pirlmarlin.service: Unit pirlmarlin.service not found.

The MN installation was performed by root and for ubuntu 16.04
It used to work fine

**Comment by plataplomo** [comment]
Would be helpful if you try to repeat this bug and tell me what steps did you take, what commands did you run, if the server is/was fresh or not. Generally, you better just wiping your server if you just want it to work again.

**Comment by plataplomo** [comment]
Last commit from phatblinkie should cause the issue as he changed service files paths to _/lib/systemd/system/pirl.service_ from _/etc/systemd/system/pirl.service_ and binaries paths as well from _/usr/local/bin_ to _/usr/bin_. Not sure how this script works now. Wait for his opinion or you can use my fork without this change https://github.com/plataplomo/pirl_mn_installer

**Comment by HaffASE** [comment]
@plataplomo Thank a lot!

**Comment by phatblinkie** [comment]
the path changes for the binary and service files are to match the paths used by the 1 click installer option on poseidon. I had several nodes that run this script and also did the one click, which made them try to start the node and marllin twice, resulting in service contention.

at this point i would recommend we make it clean up old service files to the new location rather then change it back. ultimately this script will end up turning in rpm files anyway.
